task :default => :test
desc 'Run the proof-based test'
task :test do
  sh 'test/proof'
end

desc 'Snapshot the current output as the "good" output'
task :saveproof do
  sh 'cp test/{actual,proof}.txt'
end
