task :default => :test
desc 'Run the unit and proof-based test'
task :test do
  sh 'ruby test/lib/questionnaire_spec.rb'
  sh 'test/prove'
end

desc 'Snapshot the current output as the "good" output'
task :saveproof do
  sh 'git add test/the-proof'
end
