task :default => :test
desc 'Run the proof-based test'
task :test do
  sh 'test/prove'
end

desc 'Snapshot the current output as the "good" output'
task :saveproof do
  sh 'git add test/the-proof'
end
